name: Build and Deploy BeeAlgoHive API Container

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Compile Puzzles Action
        uses: AlgoHive-Coding-Puzzles/BeeToFlow@v0.0.1
        with:
          target-directories: "puzzles, challenges, levels"
