name: Build and Deploy BeeAlgoHive API Container

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Compile Puzzles Action (BeeToFlow)
        uses: AlgoHive-Coding-Puzzles/BeeToFlow@v0.0.3
        with:
          target-directories: "B2"

      - name: Upload Compiled Files as Artifactories
        uses: actions/upload-artifact@v4
        with:
          name: compiled-puzzles
          path: |
            out/B2.tar
          retention-days: 7
