name: Build and Deploy BeeAlgoHive API Container

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Compile Puzzles Action
        uses: AlgoHive-Coding-Puzzles/BeeToFlow@v0.0.1
        with:
          target-directories: "B1, B2"

      # - name: Upload Compiled Files as Artifactories
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: compiled-puzzles
      #     path: |
      #       out/Catalog1.tar
      #       out/Catalog2.tar
      #     retention-days: 7
